Improve configgen command line handling a bit
fedimint/fedimint pull request #440
Opened 2022-08-22 04:48 UTC by dpc

Positional arguments are not descriptive and harder to use.

2022-08-22 04:49 UTC, dpc commented
Feedback (especially w.r.t naming) much appreciated.

2022-08-22 06:27 UTC, DanGould commented
Concept ACK. Much better! Consuming this script right now as well.

It makes sense for these values to have sane defaults as well. Perhaps the ones in build.sh make sense. I'm not sure what "hbbft" and "api" mean, but I'm just getting up to speed so maybe those names are good.

2022-08-22 07:53 UTC, DanGould commented
Also, what unit are the denominations? msat? That should be labeled too

2022-08-22 15:57 UTC, dpc commented
Ports and denominations should have a default.

2022-08-23 03:08 UTC, DanGould commented
fyi esplora uses default ports 5000 & 5001. Best to avoid those. Esplora pairs nicely with fedimint.

2022-08-23 04:46 UTC, dpc commented
There's 63k ports to choose from and it always have to be 8000, 8080, 3000 or some other x000. :shrug:

2022-08-23 13:24 UTC, elsirion requested changes
Really cool! Naming looks good to me. Left one idea I'd like to discuss.

2022-08-23 13:24 UTC, elsirion commented on fedimint/src/bin/configgen.rs
> +    #[clap(long = "denominations", value_delimiter = ',')]
Can we enforce that there has to be at least one denomination? Forgetting to specify them bit me a few times …

I would have assumed that this is the default behavior, but apparently it isn't (I just tested it again) and there has been a lengthy discussion about it (didn't read it all) https://github.com/clap-rs/clap/issues/1772

2022-08-24 03:09 UTC, dpc commented
`--denominations` are now required with at least on element, and ports get some randomish default values.

2022-08-24 09:40 UTC, elsirion approved these changes

2022-08-24 09:40 UTC, elsirion commented on fedimint/src/bin/configgen.rs
> +    #[clap(long = "hbbft-base-port", default_value = "17240")]
I checked that the port is out of the range for ephemeral ports on most systems (32768–60999 for Linux apparently).

2022-08-24 09:40 UTC, merged