WIP: Improve coin select logic for on-chain pegout.
fedimint/fedimint pull request #442
Opened 2022-08-22 07:40 UTC by evanlinjin

This PR uses the `CoinSelect` logic from `bdk_core` for peg-out on-chain coin selection. This fixes the previously-faulty implementation.

2022-08-24 08:52 UTC, elsirion commented
Did you copy the code from BDK? If so from where? I'd like to avoid or at least keep track of redundancy so we can get fixes if bugs are detected in BDK. Also, what's the name of the algorithm used? I assume it's one from Murch's thesis?

2022-09-08 17:50 UTC, dpc commented on modules/fedimint-wallet/src/coin_select.rs
> +impl CoinSelector {
This logic needs a lot of tests, and they should be relatively easy to write.

2022-09-08 17:51 UTC, dpc requested changes
Needs tests, IMO. :)

2022-09-20 15:04 UTC, elsirion commented
Closing for now

2022-09-20 15:04 UTC, closed without merging