New test fixtures for rust-spawned bitcoind and fake lightning
fedimint/fedimint pull request #445
Opened 2022-08-22 23:36 UTC by evanlinjin

This adds a new option for env `FM_TEST_DISABLE_MOCKS=2` which creates fixtures for a rust-spawned bitcoind (via the `bitcoind` crate) and fake lightning.

This introduces a new env `BITCOIN_EXE` in which the `bitcoind` binary can be specified. If unspecified, the `bitcoind` crate will download the binary.

`RealBitcoinTest` is now an enum, either specifying just a client, or both a service and a client (with `bitcoind::BitcoinD`).

2022-08-23 08:56 UTC, elsirion requested changes
I think this needs re-evaluation on a high level. I don't see the difference in outcome between spawning bitcoind in rust and running it internally. What I do agree with is that the tests should be more self-contained and probably not rely on externally started services (if that doesn't have other downsides, @jkitman might know).

So instead of adding this as another way of running bitcoind this should become the only way of running bitcoind in the rust integration tests (the shell tests will be unaffected). To minimize inconsistency core-lightning should be started in a similar fashion.

2022-08-23 08:56 UTC, elsirion commented on integrationtests/tests/fixtures/mod.rs
> +            info!("Testing with INTERNAL bitcoind and EXTERNAL cln");
I don't think we want the combinatorial explosion here since we'd need to test all combinations.

2022-08-23 09:16 UTC, evanlinjin commented
@elsirion Thank you for your review! Just to make sure I understand you, this should be my next steps with this PR:
* Make running `bitcoind` via rust the only way of running `bitcoind` in rust integration tests.
* Run core lightning in the same fashion.

Is this correct?

2022-08-23 13:02 UTC, elsirion commented
Yes, that's what I meant. I'd like to hear @jkitman's opinion since he built the rust integration tests, but I think starting the daemons externally is a historic artifact that we haven't gotten around to fix.

2022-08-23 16:20 UTC, dpc commented on integrationtests/README.md
> +export BITCOIN_EXE=$(which bitcoind) # We use our own bitcoind binary
`s/EXE/BIN/`?

2022-08-24 11:40 UTC, jkitman commented on integrationtests/tests/fixtures/fake.rs
> +    #[allow(dead_code)]
Why is this dead code now?

2022-08-24 11:51 UTC, jkitman commented
@evanlinjin So the advantage of using `bitcoind` is that it can be automatically downloaded and run from Rust, rather than to rely on it already running?

I would also agree with @elsirion we shouldn't have the feature flags and just switch the real fixtures to use `bitcoind` and the fake fixtures continue to use the mock bitcoin impl.

So long as all the tests can pass with `bitcoind` I don't see a problem to switching to use it.

2022-08-25 02:52 UTC, evanlinjin commented
> @evanlinjin So the advantage of using `bitcoind` is that it can be automatically downloaded and run from Rust, rather than to rely on it already running?

Yes, this is correct.

> I would also agree with @elsirion we shouldn't have the feature flags and just switch the real fixtures to use `bitcoind` and the fake fixtures continue to use the mock bitcoin impl.

Would it make sense to NOT use mock `bitcoind` service for testing? It means less code we need to maintain, and we can just test with the real thing.

Also the reason why I switched over to using feature flags is because nix did not seem to like the [`bitcoind`](https://docs.rs/bitcoind/latest/bitcoind/) crate - making it a dev dependency caused nix to claim the hashes does not add up. I do not understand nix so if I can get some guidance in this regard, it will be appreciated.

> We may also need to change the `scripts/rust-tests.sh` to avoid starting two instances of `bitcoind`.

That sounds good, I will see how I can get that done!

2022-08-26 21:37 UTC, jkitman commented
> Would it make sense to NOT use mock bitcoind service for testing

@evanlinjin the purpose of the mock was for faster testing and eliminating any shared state between tests so they can be run concurrently.  If we use `bitcoind` it will likely make tests fail if run concurrently.

2022-09-08 18:01 UTC, dpc commented
I'm marking this as blocked, as it's unclear if we can proceed with this one. Feel free to keep discussing etc. but it just makes easier for us to know which things we need to actively look into and which not.

> Also the reason why I switched over to using feature flags is because nix did not seem to like the [bitcoind](https://docs.rs/bitcoind/latest/bitcoind/) crate - making it a dev dependency caused nix to claim the hashes does not add up. I do not understand nix so if I can get some guidance in this regard, it will be appreciated.

I would be happy to help, but need more details. If you want you can ping me on Discord, or just paste some more info here.

2023-03-22 02:42 UTC, justinmoon commented
Closing this because we’ve recently started spawning everything via rust

2023-03-22 02:42 UTC, closed without merging