chore: rename `recoverytool` dir to `fedimint-recoverytool`
fedimint/fedimint pull request #5559
Opened 2024-07-01 23:00 UTC by dpc

To be consisent e.g. with `fedimint-dbtool`

2024-07-02 14:18 UTC, m1sterc001guy submitted a review, later dismissed
Do you need to change here too? https://github.com/fedimint/fedimint/blob/3d0342eaf51bf18257f5f2ff54ce7bdce6b4fa8a/nix/flakebox.nix#L593

2024-07-02 23:20 UTC, dpc commented
> Do you need to change here too?
> 
> https://github.com/fedimint/fedimint/blob/3d0342eaf51bf18257f5f2ff54ce7bdce6b4fa8a/nix/flakebox.nix#L593

Done in a different PR that already landed.

2024-07-03 13:43 UTC, tvolk131 requested changes

2024-07-03 13:43 UTC, tvolk131 commented on fedimint-recoverytool/Cargo.toml
Nit: can we change the description here:

https://github.com/fedimint/fedimint/blob/070aa1ac5e6842e8c595d3cab41605875c7f9912/fedimint-recoverytool/Cargo.toml#L6

to something like: `tool for retrieving on-chain funds from a offline federation`

2024-07-03 19:43 UTC, tvolk131 approved these changes

2024-07-03 20:02 UTC, merged