test: LNv2 add mint to mint test
fedimint/fedimint pull request #5650
Opened 2024-07-16 03:55 UTC by m1sterc001guy

Working towards https://github.com/fedimint/fedimint/issues/5490

Adds some test cases where a client in one federation can pay a client in a different federation.

This doesn't fundamentally add coverage to new code paths, since LNv2 treats this test case as the same, but I think its a cool test to have, and can serve as a nice check in the future to make sure this use case does not break.

2024-07-16 03:59 UTC, dpc approved these changes

2024-07-16 09:00 UTC, joschisan requested changes
This test should be written as a loop over all four possible combinations of gateways like the self payment test.

2024-07-16 12:14 UTC, joschisan commented
Maybe we should call this test_inter_federation_payment?

2024-08-06 16:05 UTC, joschisan approved these changes

2024-08-06 16:44 UTC, dpc approved these changes

2024-08-06 17:10 UTC, merged