fix: add transaction fee
fedimint/fedimint pull request #5837
Opened 2024-08-12 10:13 UTC by joschisan

2024-08-13 13:36 UTC, elsirion requested changes
Imo the proper way of introducing this, as discussed on our call, would be:

* Create static `tx_fees` API endpoint, that always returns 0 (we can only turn it on in 2 versions)
* Implement syncing to client DB from that endpoint, ideally in a generic enough way that will allow us to treat module fees the same way in another PR
* Use the (currently 0) value in the client, make sure in tests that setting it to non-zero works with the current client
* Eventually implement the server side that allows setting a non-zero fee (likely through some consensus voting)

2024-08-13 13:36 UTC, elsirion commented on fedimint-client/src/db.rs
> +
I think in retrospect it was a mistake to patch in `broadcast_public_keys` into the client config. As discussed with @dpc we should add new config as API endpoints and sync it to the client. This has the additional benefit of allowing us to update values by re-fetching it from time to time.

2024-08-14 07:57 UTC, joschisan commented
@elsirion I would prefer to merge this as is. I have no plans to make the transaction fee in the consensus dynamic as it will be negligible in regular use, especially compared to lightning fees, therefore this value is just as static as many other values currently in the client config. If you want to turn the client config into an endpoint at a later point be my guest, I am not contesting that, however, doing it with this pr is not the right place. This pr is a consensus change that needs to be supported by the client and therefore not the place to change client behaviour like how config values are fetched.

2024-08-14 20:41 UTC, elsirion commented
By going the API path a lot of the client changes become redundant, hence my hesitancy to merge as-is. If we make the fee a new DB entry we won't need the DB migration anymore, but do we want to remove it again once it was on master? We could, it's just a lot of back and forth that will mess up people's DBs in the process.

2024-10-22 15:53 UTC, closed without merging