chore: use typed errors in LNv2
fedimint/fedimint pull request #5923
Opened 2024-08-26 19:13 UTC by m1sterc001guy

Small ergonomic improvement, gives us some nice spans in the logs, can re-use `select_client` and get stack traces in the logs

2024-08-31 16:15 UTC, elsirion approved these changes
One nit

2024-08-31 16:15 UTC, elsirion commented on gateway/ln-gateway/src/lib.rs
> +        info!("JUMOELL received request for routing info");
Do you want to keep your name in here?

2024-09-01 13:40 UTC, tvolk131 approved these changes
Nice cleanups here! My only thought is that the PR name (and matching commit name) only reflect a subset of what's here. Could be worth renaming.

2024-09-02 17:02 UTC, joschisan requested changes
Do not merge it like this. The gateways endpoints for the client return a string error since the user client will neither branch on those nor display the specifics to the user. The implication for the user is always to try a different gateway. Furthermore, the current GatewayError enum contains many variants that have nothing to do with a users ln payment.

The errors are only for debugging and need to maintain backwards compatibility here with the clients so we should use a string here.

2024-09-03 19:38 UTC, m1sterc001guy commented
From our call this morning. @joschisan add anything I missed.

1. Removal of wrapped `Result` is a good improvement, but the current state of error handling is still a bit confusing. After this PR we will:
 - Separate `GatewayError` into 3 error types: LNv1, LNv2, and GatewayAdmin error types. 
 - Each error type will log in `into_response` when returning the `Response` back to the client. 
 - Privacy sensitive errors like LNv1 and LNv2 will map error enums to error codes and messages like we do today. 
 - `GatewayAdmin` errors will return the full error back to the client for debugging purposes
 - Cleanup and consolidate error types.

2024-09-04 15:45 UTC, joschisan submitted a review, later dismissed

2024-09-04 17:02 UTC, merged