refactor: gateway error refactor
fedimint/fedimint pull request #6051
Opened 2024-09-20 15:51 UTC by m1sterc001guy

See https://github.com/fedimint/fedimint/pull/5923#issuecomment-2327284866 for additional context.

This PR refactors how we handle errors in the gateway. Previously, we just had a `GatewayError` type where we dumped all of our error types. Most of these would be redacted before returning to the client, which kind of defeats the purpose of using typed errors.

This PR adds two error types: `PublicGatewayError` and `AdminGatewayError`. `AdminGatewayError` error messages and full details are always returned to the client. The intention is that this error type is used for authenticated endpoints only. Unauthenticated endpoints, such as what is used in LNv1 and LNv2, should use `PublicGatewayError`, which has the specific details of the error redacted for privacy reasons.

Both error types always log so the gateway operator can check the logs for full description of an error.

Open to feedback on the design if anyone has strong opinions.

2024-09-21 14:37 UTC, elsirion approved these changes
Concept ACK

2024-09-23 19:44 UTC, tvolk131 requested changes
A few nits. Also how difficult would it be to add a test that attempts to call an authenticated route without being authenticated and verify that the `AdminGatewayError` isn't returned? That would also ensure that the authentication middleware is working correctly.

2024-09-23 19:44 UTC, tvolk131 commented on gateway/ln-gateway/src/error.rs
> +pub enum AdminGatewayError {
Nit: Please document

2024-09-23 22:56 UTC, tvolk131 approved these changes

2024-09-23 23:21 UTC, merged