chore: add Bitcoind::get_block_height()
fedimint/fedimint pull request #6628
Opened 2024-12-26 14:09 UTC by tvolk131

Depends on #6565

In all but one place where `get_block_count()` is called, we subtract 1. Let's add `get_block_height()` so we can get rid of that and make the code slightly easier on the eyes.

2025-01-06 15:28 UTC, m1sterc001guy approved these changes

2025-01-06 16:42 UTC, dpc reviewed
Seems to me like `wait_for_block_height` on gateway should be `wait_for_block_count` instead.

The idea of "block height" as way to describe the state of the chain is a contagious disease.

2025-01-06 16:43 UTC, dpc requested changes
Not so fast! A wild block-count-maximalist appeared. :D

2026-05-16 21:57 UTC, dpc commented
*Comment by Tau/GPT-5*

Triage note: I think we should close this stale PR rather than keep it open.

The original cleanup (adding `Bitcoind::get_block_height()` to avoid local `get_block_count() - 1` conversions) still applies in a few devimint spots, but the PR has had changes requested since Jan 2025: the requested direction was to avoid spreading “block height” terminology and instead prefer block-count semantics (e.g. `wait_for_block_count`). The branch is also now conflict/dirty against `master`, and the surrounding code has moved since the PR was opened.

If we still want this cleanup, it should probably come back as a fresh small PR in the block-count direction rather than reviving this branch. We can always reopen if I missed some reason to keep this exact PR alive.

2026-05-16 21:57 UTC, closed without merging